### ISSUE TITLE
Target in wrong place in virtual space

### ISSUE THREAD

**Issue by mungewell** [JDelekto/VRTestPattern#2]
Appreciate that this is an old project, but thought it might help me with a DIY project based around VRidge API.

The target is displayed and can be moved with up/down cursors, but it is oddly placed - not directly infront of me as would be expected.

Is there a way to move it's location, or what location should the viewing location be?
![target_wrong_position](https://user-images.githubusercontent.com/236907/99161690-aa865600-26ec-11eb-9c0f-0068cfa6e051.png)

**Comment by JDelekto** [comment]
Hello!
I haven't revisited this project in quite some time, so I am not sure if there is anything that should have changed over time as the APIs have changed.
The original purpose of this project was to display a test pattern that could be used for hand-modification of the lens distortion parameters (without actual equipment calibration) back when the Samsung Gear lens modification was briefly popular for the original Vive.
There are two modes for the pattern, one which is parented to the HMD (not sure if this might be what is missing) or if it is not parented) and this can be toggled by using the '1' and '2' keys on the keyboard.
Cheers!
==============

    On Saturday, November 14, 2020, 09:46:58 PM EST, mungewell <notifications@github.com> wrote:  
 
 


Appreciate that this is an old project, but thought it might help me with a DIY project based around VRidge API.

The target is displayed and can be moved with up/down cursors, but it is oddly placed - not directly infront of me as would be expected.

Is there a way to move it's location, or what location should the viewing location be?

**Comment by mungewell** [comment]
Pressing "2" positioned the target right in-front of the headset. Thanks.

BTW: I am attempting to figure out lens parameters for a DIY solution based around VRidge and the PSVR headset.

**Comment by JDelekto** [comment]
Cool.  It was a quick little mini-project; I haven't done as much VR development as I had hoped.
Good luck with your project!
====================
    On Sunday, November 15, 2020, 11:49:39 AM EST, mungewell <notifications@github.com> wrote:  
 
 


Pressing "2" positioned the target right in-front of the headset. Thanks.

BTW: I am attempting to figure out lens parameters for a DIY solution based around VRidge and the PSVR headset.
